sudo: required

language: python

python: 3.5

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35

script:
    - tox -e $TOX_ENV

install:
    - pip install tox

notifications:
  email:
    on_success: change
    on_failure: always